language: node_js

node_js:
  - '12'
  - '14'
  - '15'

branches:
  only:
    - master
    - travis-ci

install:
  - npm install --no-package-lock --no-save
  - npm install -g nyc prove
  - node test/aardvark.wpt.t.js

script:
  - nyc npm test
